
package it.unipv.view;
import javax.swing.JButton;
public class Menuprincipale extends javax.swing.JFrame {

    /**
     * Creates new form Menuprincipale
     */
    public Menuprincipale() {
        initComponents();
         this.setTitle("MENU PRINCIPALE");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Buttongestionepaziente = new javax.swing.JButton();
        Buttongestioneappuntamenti = new javax.swing.JButton();
        Buttongestionetrattamenti = new javax.swing.JButton();
        Buttongestioneprescrizioni = new javax.swing.JButton();
        Buttongestionefattura = new javax.swing.JButton();
        Buttongestionestatistica = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Buttontornaindietro1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/logologin.png"))); // NOI18N
        jLabel1.setText("Dental Us");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        Buttongestionepaziente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestionepaziente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/gestionepaziente.png"))); // NOI18N
        Buttongestionepaziente.setText("Pazienti");
        Buttongestionepaziente.setBorderPainted(false);
        Buttongestionepaziente.setContentAreaFilled(false);
        Buttongestionepaziente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestionepaziente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestionepaziente);

        Buttongestioneappuntamenti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestioneappuntamenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/appuntamenti.png"))); // NOI18N
        Buttongestioneappuntamenti.setText("Appuntamenti");
        Buttongestioneappuntamenti.setBorderPainted(false);
        Buttongestioneappuntamenti.setContentAreaFilled(false);
        Buttongestioneappuntamenti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestioneappuntamenti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestioneappuntamenti);

        Buttongestionetrattamenti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestionetrattamenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/trattamenti.png"))); // NOI18N
        Buttongestionetrattamenti.setText("Trattamenti");
        Buttongestionetrattamenti.setBorderPainted(false);
        Buttongestionetrattamenti.setContentAreaFilled(false);
        Buttongestionetrattamenti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestionetrattamenti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestionetrattamenti);

        Buttongestioneprescrizioni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestioneprescrizioni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/gestioneprescrizione.png"))); // NOI18N
        Buttongestioneprescrizioni.setText("Prescrizioni");
        Buttongestioneprescrizioni.setBorderPainted(false);
        Buttongestioneprescrizioni.setContentAreaFilled(false);
        Buttongestioneprescrizioni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestioneprescrizioni.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestioneprescrizioni);

        Buttongestionefattura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestionefattura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/fattura.png"))); // NOI18N
        Buttongestionefattura.setText("Fattura");
        Buttongestionefattura.setBorderPainted(false);
        Buttongestionefattura.setContentAreaFilled(false);
        Buttongestionefattura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestionefattura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestionefattura);

        Buttongestionestatistica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttongestionestatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unipv/view/statistiche.png"))); // NOI18N
        Buttongestionestatistica.setText("Statistica");
        Buttongestionestatistica.setBorderPainted(false);
        Buttongestionestatistica.setContentAreaFilled(false);
        Buttongestionestatistica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buttongestionestatistica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Buttongestionestatistica);

        Buttontornaindietro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Buttontornaindietro1.setText("Torna Indietro");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buttontornaindietro1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(Buttontornaindietro1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public JButton getButtongestionepaziente(){
 return Buttongestionepaziente;
 }
     
     
  public JButton getButtongestioneappuntamenti(){
 return Buttongestioneappuntamenti;
 }
 
   public JButton getButtongestionetrattamenti(){
 return Buttongestionetrattamenti;
 }
  
  public JButton getButtongestioneprescrizioni(){
 return Buttongestioneprescrizioni;
 }
  
  public JButton getButtongestionefattura(){
 return Buttongestionefattura;
 }
  
  public JButton getButtongestionestatistica(){
 return Buttongestionestatistica;
 }
  
    public JButton getButtontornaindietro1(){
 return Buttontornaindietro1;
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttongestioneappuntamenti;
    private javax.swing.JButton Buttongestionefattura;
    private javax.swing.JButton Buttongestionepaziente;
    private javax.swing.JButton Buttongestioneprescrizioni;
    private javax.swing.JButton Buttongestionestatistica;
    private javax.swing.JButton Buttongestionetrattamenti;
    private javax.swing.JButton Buttontornaindietro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
